### ISSUE TITLE
Idea: Using the container-based Travis CI build system

### ISSUE THREAD

**Issue by blzysh** [codecov/example-bash#8]
I had some issues with the gcloud versions on the VM Travis CI build systems so I've switched to using the following slimmed down travis.yml with codecov. I'm new to all this but maybe this will help someone else who wants to continue to use the container-based build system with kcov & codecov?

```yaml
sudo: false

addons:
  apt:
    packages:
      - binutils-dev
      - libcurl4-openssl-dev
      - libdw-dev
      - libiberty-dev

language: bash

env:
- PATH=${PATH}:${HOME}/kcov/bin 

before_install:
- wget https://github.com/SimonKagstrom/kcov/archive/master.tar.gz

install:
- tar xzf master.tar.gz
- cd kcov-master
- mkdir build
- cd build
- cmake -DCMAKE_INSTALL_PREFIX=${HOME}/kcov ..
- make
- make install
- cd ../..
- rm -rf kcov-master
- mkdir -p coverage

script:
- kcov coverage test.sh

after_success:
- bash <(curl -s https://codecov.io/bash)
```
I might see if caching speeds up the build too.
